name: Metrics
on:
  # Обновление каждый день
  schedule: [{cron: "0 0 * * *"}]
  # Возможность запустить вручную
  workflow_dispatch:
  # Запуск при пуше в main/master
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Замените на ваш username
          user: Granzh
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Moscow

          # Плагины
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_achievements: yes
          plugin_achievements_threshold: C